name: CI Test
on:
  push:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  push-test:
    name: 코드를 빌드 및 테스트 진행
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17 
        
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.3.3

    - name: Gradle Test
      run: ./gradlew test
      
      
